import { chromium } from 'playwright';
import fs from 'fs';
const HTML = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8').replace(/const RELAY_BASE = "[^"]*";/, 'const RELAY_BASE = "http://127.0.0.1:8787/";');
const b = await chromium.launch(); const page = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.route('**/*', r => { const u = r.request().url();
  if (u.startsWith('http://localhost:8080')) return r.fulfill({ status: 200, contentType: 'text/html', body: HTML });
  if (u.startsWith('http://127.0.0.1:8787')) return r.continue();
  return r.abort(); });
await page.goto('http://localhost:8080/'); await page.waitForTimeout(800);
const R = {};
R.gearHidden = await page.$$eval('#layer-chips [data-akey]', els => els.length === 0);
await page.evaluate(() => { if (!state.layers.ships) toggleLayer('ships'); });
await page.waitForTimeout(3500);
R.status = await page.evaluate(() => state.layerStatus.ships + ' ships=' + state.layerData.ships.length + ' msgs=' + state.ais.msgs);
R.diag = await page.evaluate(() => state.ais.diag);
R.chip = await page.$$eval('#layer-chips .lchip', els => els.map(e => e.textContent.trim()).filter(t => t.startsWith('Ships')));
R.name = await page.evaluate(() => (state.layerData.ships[0] || {}).name + ' t-age-ms=' + (Date.now() - (state.layerData.ships[0] || {}).t));
await page.evaluate(() => setSelected('iran')); await page.waitForTimeout(2500);
const st = await (await fetch('http://127.0.0.1:8787/ais/status')).json();
R.relayAfterSelect = 'clients=' + st.clients + ' extraBoxes=' + st.extraBoxes + ' diag=' + st.diag;
R.socketStillSame = await page.evaluate(() => state.ais.ws && state.ais.ws.readyState === 1);
R.signals = await page.$eval('#d-signals', el => el.innerText.replace(/\s+/g, ' ').slice(0, 140));
R.air = await page.evaluate(() => state.airDiag);
console.log(JSON.stringify(R, null, 2)); console.log('PAGE ERRORS:', errs.length ? errs : 'none');
await b.close();
